### ISSUE TITLE
Transfer user manuals from the old version and improve it (e.g., using Wiki)

### ISSUE THREAD

**Issue by quantum-entangled** [quantum-entangled/machine-learning-ui#16]
Come up with a better way of storing and dealing with our developer and user documentations.

**Comment by CKPEIIKA** [comment]
Options:
https://www.sphinx-doc.org/en/master/  (can generate TeX)
https://www.mkdocs.org/

If project was open-source than it would be possible to use these hosting solutions for free:
https://readthedocs.com/
https://www.gitbook.com/

**Comment by quantum-entangled** [comment]
It's kind of open-source, but I'm not sure haha. Sphinx seems to be the good option for our developer-docs, cause it's capable to process Python own docstring, which is closely related to #3. There are other options too, like pydoc, for example. I've never actually used any of these, so some experience is appreciated. As for user guides, their main purpose is to acquaint our users with the whole app (like which buttons to click, what to right, etc.), so they should probably be within app itself, like in markdown or separate Readme, but other web-hosts may be great too.

**Comment by CKPEIIKA** [comment]
The user guide can be part of generated documentation as well as included within. When the core of the project will acquire well-defined structure and some decision about specific options will be made, i can work on docs.

**Comment by quantum-entangled** [comment]
Ok, thank you, I'll keep it on mind.
