### ISSUE TITLE
DataGridWidget (specifically, ipydatagrid) is taken too long to render the huge dataset

### ISSUE THREAD

**Issue by quantum-entangled** [quantum-entangled/machine-learning-ui#2]
It's taken some time (around 2-3 minutes) to render a dataset of about 40000 rows and 100 columns. Maybe we should somehow limit the number of rows and columns to show or dig into the probable solutions via the library itself.

For the moment, we are using the latest [ipydatagrid 1.1.13](https://github.com/bloomberg/ipydatagrid).

**Comment by CKPEIIKA** [comment]
Do we need to load such a huge datagrid at all? Probably .head(1000) will fit for preview. Otherwise "load x rows starting from y" can be implemented.

**Comment by quantum-entangled** [comment]
Resolved in #43

**Comment by quantum-entangled** [comment]
Resolved in #43
