### ISSUE TITLE
Add minimal working example

### ISSUE THREAD

**Issue by CKPEIIKA** [quantum-entangled/machine-learning-ui#20]
So far I haven't been able to get anything to run, it can be very helpful to see something that _should_ run and involves all stages of UI. Probably something like manual for TCs_air5.txt from the previous version can fit well.

**Comment by quantum-entangled** [comment]
Yes, I apologize if it's the problem for now, I'm trying to make the whole app ASAP. After that it would make sense to add some end-to-end examples, illustrating the whole pipeline. But for now it will be helpful if you specify what exactly is the problem with running the application. Cause it's more likely to be the problem with your environment.
