### ISSUE TITLE
Add Show Data Statistics module in Data Preparation section

### ISSUE THREAD

**Issue by quantum-entangled** [quantum-entangled/machine-learning-ui#41]
Add an option to show some relevant data statistics to explore the dataset.

**Comment by CKPEIIKA** [comment]
Will pd.describe() be enough?

**Comment by quantum-entangled** [comment]
> Will pd.describe() be enough?

Yes, I've also thought of this in the first place. And I suppose we should also include `info()` in order to see the number of columns, dtypes, etc.
