### ISSUE TITLE
Problem with Binder links inside the app

### ISSUE THREAD

**Issue by quantum-entangled** [quantum-entangled/machine-learning-ui#45]
It seems like Binder uses different hubs and its prefixes (e.g. `hub-binder` or `hub.gke2`) for launching notebooks, which leads to errors with current links construction inside `main.ipynb`. I haven't really found the solution on how to get current URL string or current Binder Hub, only Jupyter server. This is a problem to Voila, cause it contains only "true" UI, and anything else should be reached by specific links.

**Comment by quantum-entangled** [comment]
@CKPEIIKA, can you, please, take a look at this as next step?

**Comment by quantum-entangled** [comment]
> What is the problem with using relative paths?

It doesn't work on Binder, cause Binder process such links in a strange manner, adding `files=` prefix. I was thinking about hard-coding its Url, but turns out that there are different hubs, so no uniform link address. 

Searched for some solutions, including `%%javascript` magic function, but none of them really worked, the only potential was to get current Jupyter server path, which was working via `list(notebookapp.list_running_servers())[0]`, so it's strange that you're getting an error. That possibly means you haven't activated the server itself. But nevertheless it doesn't solve the hub problem.

**Comment by CKPEIIKA** [comment]
I mean using `FileLink(datasets_url)`. It works for me in the binder at least without voila.

**Comment by quantum-entangled** [comment]
Yes, it works for files, but the main concern is to get the folder path link of Datasets/Models/etc. in order to allow users to upload files/models initially to the server itself, and then use it inside the app. And that's not the problem for Jupyter Notebook or Lab usage, you just find the folder in filesystem, but for Volia everything is "encapsulated" inside the UI, so we need links to specific folders.

**Comment by CKPEIIKA** [comment]
I checked it: now everything is fine. However i am not sure that the needed notebook always would be first at the list locally. But as it was mentioned it is not so important to have these links in "casual" ui.
What about nbgitpuller, it can be useful to pay attention anyway:
https://discourse.jupyter.org/t/tip-speed-up-binder-launches-by-pulling-github-content-in-a-binder-link-with-nbgitpuller/922

**Comment by quantum-entangled** [comment]
> I checked it: now everything is fine. However i am not sure that the needed notebook always would be first at the list locally. But as it was mentioned it is not so important to have these links in "casual" ui.

I will look for some other ways of getting current server base_url and probably test different approaches, but hopefully it's working.

> What about nbgitpuller, it can be useful to pay attention anyway:
> https://discourse.jupyter.org/t/tip-speed-up-binder-launches-by-pulling-github-content-in-a-binder-link-with-nbgitpuller/922

I've read about it a bit, but not sure if we should use this approach. Cause dividing the repos will require local users to install and merge them again, if users don't use Git. And it becomes a bit redundant, since there is no problem to install app and env locally. However, Binder could definitely gain some benefits from such separation, but I would suggest using just version tags for a launch, when we'll get some stable versions.
